name = "dns-sub"                    
main = "src/index.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "dns-sub"
database_id = "549968ea-f223-4fd7-a16d-5ba11d93c75c"

[triggers]
crons = ["0 0 * * *"]

[vars]
APP_NAME = "DNS-SUB"                      # 顺手改掉
JWT_EXPIRE_SECONDS = "86400"
APPLINK_EXPIRE_SECONDS = "300"
CI_TOKEN_EXPIRE_SECONDS = "1800"
GITHUB_OWNER = "alay2022"          # ← 如果以后配证书续签
GITHUB_REPO = "dns-sub"
GITHUB_REF = "main"
OAUTH_REDIRECT_BASE = "https://api.ztvps.com"   # ← 用你的实际子域
FRONTEND_BASE = "https://vip.ztvps.com"   # 以后 Pages 前端的地址，先留着